#!/bin/sh
# Alias file that is Bash and Fish intercompatible

# MY ALIASES BEGIN

# vi < vim < nvim substituton
export EDITOR='vi'
export VISUAL='vi'
command -v vim >/dev/null && \
export EDITOR='vim' && \
export VISUAL='vim' && \
alias vi='vim'
# command -v nvim >/dev/null && \
# export EDITOR='nvim' && \
# export VISUAL='nvim' && \
# alias vim='nvim'

# Set Absible config folder
export ANSIBLE_CONFIG="$HOME/.ansible/ansible.cfg"
# Use QEMU system URI
export LIBVIRT_DEFAULT_URI="qemu:///system"
# MCfly history settings
export MCFLY_RESULTS=30
export MCFLY_PROMPT="❯"
export MCFLY_FUZZY=5

## MY ALIASES
alias dus='du -h --max-depth 1'
# Force tmux color
alias tmux='tmux -2'
alias tmux-new='tmux -2 new -s '
# alias tmux-reatch="tmux -2 attach -t $(tmux ls | awk '{print $1}' | sed 's/://g' | fzf)"

# Fuzzy Finder scripts
command -v fzf >/dev/null && \
# Fuzzy find dev directory type, then projects
alias dev='cd $(find ~/dev/* -maxdepth 1 -type d | fzf)' && \
# Fuzzy find dev directory all
alias deva='cd $(find ~/dev/* -type d | fzf)' && \
# Config folder fuzzy find
alias conf='cd $(find ~/.config/* -maxdepth 0 -type d | fzf)' && \
# Config folder fuzzy find all
alias confa='cd $(find ~/.config/* -type d | fzf)' && \
# Log tailer
alias logt='tail -f $(find /var/log -type f | fzf)' && \
# Journalctl process log tailer
alias logj='ps aux | fzf | awk "{print $2}" | xargs -I % sudo sh -c journalctl _PID=%' && \
# Process killer
alias pkl='ps aux | fzf --header "Please select what process to kill" | awk "{print $2}" | xargs kill'

# Pass gen
# alias pass-gen='< /dev/urandom tr -dc _A-Z-a-z-0-9 | head -c' # $1 - number of bytes

# Sudo aliases
# List SSH sessions
alias lsssh="sudo netstat -tnpa | grep 'ESTABLISHED.*sshd'"
alias lsprt="sudo lsof -i -P -n"

# Python aliases
alias pip-install='pip install --upgrade --no-cache pip wheel setuptools '
alias python-venv='python3 -m venv venv && source ./venv/bin/activate'
alias python-https-server='python3 ~/dev/HTTPSPythonServer/server-start.py'
alias dj-migrate='python manage.py makemigrations && python manage.py migrate'
alias pip-req-txt-to-toml="echo 'Adding requirements.txt to pyprpoject.toml' && cat requirements.txt | grep -E '^[^# ]' | cut -d= -f1 | xargs -n 1 poetry add"

# Rust aliases
alias clpy='cargo clippy -- -W clippy::pedantic -W clippy::nursery -W clippy::unwrap_used'
alias clpy-fix='cargo clippy --fix --allow-dirty -- -W clippy::pedantic -W clippy::nursery -W clippy::unwrap_used'

# Docker aliases
alias dk='docker'
alias dkup='sudo systemctl start docker.service'
alias dkdown='sudo systemctl stop docker.service'
alias dkstop="docker ps -a --format 'table {{.ID}}\t{{.Names}}\t{{.Image}}\t{{.RunningFor}}' | fzf --header 'Please select which container to stop' | cut -f 1 -d ' ' | xargs -I % sh -c 'docker stop %'"
alias dkstopA='docker ps -a -q | xargs docker stop'
alias dkrm="docker ps -a --format 'table {{.ID}}\t{{.Names}}\t{{.Image}}\t{{.RunningFor}}' | fzf --header 'Please select which container to remove' | cut -f 1 -d ' ' | xargs -I % sh -c 'docker rm %'"
alias dkrmA='docker ps -a -q | xargs docker rm'
alias dkrmi="docker images -a --format 'table {{.ID}}\t{{.Repository}}:{{.Tag}}\t{{.CreatedSince}}\t{{.Size}}' | fzf  --header 'Please select which volume to remove' | cut -f 1 -d ' ' | xargs -I % sh -c 'docker rmi %'"
alias dkrmiA='docker images -a -q | xargs docker rmi'
alias dkvolrmA='docker system prune --volumes --all --force'
alias dkpruneA='dkstopA && dkrmA && docker image prune'

# Mount rclone
alias rclone-crypt='rclone mount crypt:/ ~/Desktop/crypt/ --read-only --max-read-ahead=1G --acd-templink-threshold=0 --contimeout=15s --checkers=16 --bwlimit=0 --retries=3 --timeout=30s --low-level-retries=1 --transfers=8 --dir-cache-time=30m'
alias mi-display-fix='xrandr --output HDMI-0 --mode 3440x1440 --rate 60'

# Extract GPS data from image with imagemagick
# $1 file name
alias image-gps='identify -format "%[EXIF:GPSLatitude],%[EXIF:GPSLongitude]\n" '

# Git aliases
alias g='git'
alias gst='git status'
alias gf='git diff'
alias gF='git diff --staged'
alias gl="git log --graph --abbrev-commit --decorate --format=format:'%C(bold blue)%h%C(reset) - %C(bold cyan)%aD%C(reset) %C(bold green)(%ar)%C(reset)%C(auto)%d%C(reset)%n''          %C(white)%s%C(reset) %C(dim white)- %an%C(reset)'"
alias ga='git add '
alias gai='git add --interactive'
alias gA='git add -A'
alias gcm='git commit'
alias gcM='git commit --amend'
alias gp='git push'
alias gP='git push --force'
alias gsubu='git submodule update --recursive --remote'
# Use fuzzy finder to select a range from 1 to 20 to soft reset HEAD~X
alias gS="seq 1 20 | fzf --header 'HEAD~n number to soft reset' | xargs -I % sh -c 'git reset --soft HEAD~%'"
# Use fuzzy finder to select a range from 1 to 20 to hard reset HEAD~X
alias gH="seq 1 20 | fzf --header 'HEAD~n number to hard reset' | xargs -I % sh -c 'git reset --hard HEAD~%'"
# Use fuzzy finder to select a range from 1 to 20 to rebase HEAD~X
alias gR="seq 1 20 | fzf --header 'HEAD~n number to rebase' | xargs -I % sh -c 'git rebase -i HEAD~%'"
# Use fuzzy finder to select what git branch to checkout 
alias gchk="git branch --format='%(refname:short)' | fzf --header 'Select branch to checkout' | xargs -I % sh -c 'git checkout %' "

## Useful aliases
# Replace ls with exa
command -v exa >/dev/null && \
# preferred listing
alias ls='exa -al --color=always --group-directories-first --icons' && \
# all files and dirs
alias la='exa -a --color=always --group-directories-first --icons' && \
# long format
alias ll='exa -l --color=always --group-directories-first --icons' && \
# tree listing
alias lt='exa -aT --color=always --group-directories-first --icons' && \
# show only dotfiles
alias l.='exa -a | egrep"^\."'
# Ip with colors
alias ip='ip -color'

# Replace some more things with better alternatives
command -v pygmentize >/dev/null && alias cat='pygmentize -g '
command -v bat >/dev/null && alias cat='bat --style header --style snip --style changes --style header'
[ ! -x /usr/bin/yay ] && [ -x /usr/bin/paru ] && alias yay='paru'

# Common use
alias grubup='sudo update-grub'
alias tarnow='tar -acf '
alias untar='tar -xvf '
alias wget='wget -c '
alias psmem='ps auxf | sort -nr -k 4'
alias psmem10='ps auxf | sort -nr -k 4 | head -10'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias ......='cd ../../../../..'
alias dir='dir --color=auto'
alias vdir='vdir --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias hw='hwinfo --short'                          # Hardware Info
alias please='sudo'
alias tb='nc termbin.com 9999'

# Bindings for Arch
command -v pacman >/dev/null && \
  alias rmpkg='sudo pacman -Rdd' && \
  # Sort installed packages according to size in MB
  alias big='expac -H M "%m\t%n" | sort -h | nl' && \
  # List amount of -git packages
  alias gitpkg='pacman -Q | grep -i "\-git" | wc -l' && \
  # Get fastest mirrors
  alias mirror="sudo reflector -f 30 -l 30 --number 10 --verbose --save /etc/pacman.d/mirrorlist" && \
  alias mirrord="sudo reflector --latest 50 --number 20 --sort delay --save /etc/pacman.d/mirrorlist" && \
  alias mirrors="sudo reflector --latest 50 --number 20 --sort score --save /etc/pacman.d/mirrorlist" && \
  alias mirrora="sudo reflector --latest 50 --number 20 --sort age --save /etc/pacman.d/mirrorlist" && \
  # Help people new to Arch
  alias apt='echo "Bruh, you are using Arch, btw" ' && \
  alias apt-get='echo "Bruh" ' && \
  # Cleanup orphaned packages
  alias cleanup='sudo pacman -Rns (pacman -Qtdq)' && \
  # Recent installed packages
  alias rip="expac --timefmt='%Y-%m-%d %T' '%l\t%n %v' | sort | tail -200 | nl"

# Get the error messages from journalctl
alias jctl="journalctl -p 3 -xb"


