#!/usr/bin/env bash

script_id="mbrav/dotfiles installer"
script_dir="$(dirname "$(realpath "$0")")"
dot_dir="$(realpath "${script_dir}/../../../")"

# Source util functions
source "${script_dir}/_util"

function dotfiles_symlink() {
	# List conf files in .config
	local dir_ls=($(ls -A "$dot_dir/dotfiles/.config"))

	# Loop through contents
	for item in "${dir_ls[@]}"; do
		# Check item full path
		local item_path="$dot_dir/dotfiles/.config/$item"
		if [ -f $item_path ] || [ -d $item_path ] && [ -z "$force" ]; then
			info_msg "Item $item_path exists"
			yes_no_prompt "${GREEN}Replace $item_path with new symlink?${YELLOW}" &&
				rm -rfv "$HOME/.config/$item" &&
				ln -sv "$item_path" "$HOME/.config/$item"
		else
			info_msg "Symlinking file $item_path to $HOME/.config/$item"
			rm -rfv "$HOME/.config/$item"
			ln -sv "$item_path" "$HOME/.config/$item"
		fi
	done

	# List conf files in home without folders
	local dir_ls=($(ls -Ap "$dot_dir/dotfiles" | grep -v /))

	for item in "${dir_ls[@]}"; do
		local item_path="$dot_dir/dotfiles/$item"
		if [ -f $item_path ] || [ -d $item_path ] && [ -z "$force" ]; then
			info_msg "Item $item_path exists"
			yes_no_prompt "${GREEN}Replace $item_path with new symlink?${YELLOW}" &&
				rm -fv "$HOME/$item" &&
				ln -sv "$item_path" "$HOME/$item"
		else
			info_msg "Symlinking file $item_path to $HOME/$item"
			rm -fv "$HOME/$item"
			ln -sv "$item_path" "$HOME/$item"
		fi
	done
}

ran_col_str "${script_id} installer"
if [[ -z "$force" ]]; then
	warning_msg "Script in interative mode. Use force=1 ./install.sh for non-interactive install"
	yes_no_prompt "${GREEN}Install Dotfiles as symlinks? ${YELLOW}" &&
		dotfiles_symlink
else
	info_msg "Installing dotfiles non-interactively"
	dotfiles_symlink
fi

[[ $? -ne 0 ]] && error_msg "Failed to install dotfiles" 1 ||
	success_msg "Dotfiles install successfuly! Reload shell."

exit 0
