# See https://k9scli.io/topics/config/
k9s:
  liveViewAutoRefresh: true
  screenDumpDir: /tmp/k9s-screens
  refreshRate: 2
  apiServerTimeout: 15s
  maxConnRetry: 5
  readOnly: false
  defaultView: ""
  noExitOnCtrlC: true
  portForwardAddress: localhost
  ui:
    enableMouse: true
    headless: false
    logoless: false
    crumbsless: false
    reactive: false
    noIcons: false
    skin: nord
  skipLatestRevCheck: false
  disablePodCounting: false
  shellPod:
    image: busybox:1.35.0
    namespace: default
    limits:
      cpu: 100m
      memory: 100Mi
    tty: true
  imageScans:
    enable: true
    exclusions:
      namespaces: []
      labels: {}
  logger:
    tail: 500
    buffer: 5000
    sinceSeconds: -1
    textWrap: true
    showTime: false
  thresholds:
    cpu:
      critical: 90
      warn: 75
    memory:
      critical: 90
      warn: 75
